fixed a bizzare MSVC error, where a label was not defined in an asm block, it said "C:/Games/eleven/source/other/planet3d.cpp(916) : error C2443: operand size conflict" repeatedly.  Silly rabbit.